"""McGill faculty and department registry."""

from __future__ import annotations

ALL_FACULTIES: list[tuple[str, str, list[str]]] = [
    (
        "Agricultural & Environmental Sciences",
        "agri-env-sci",
        [
            "AGRI",
            "ANSC",
            "BIEN",
            "FDSC",
            "FMGT",
            "PARA",
            "PLNT",
            "NRSC",
            "AEBI",
            "AEMA",
            "ABEN",
            "LSCI",
            "AECH",
            "AEHM",
            "AEIS",
            "AEPH",
            "AGEC",
            "BTEC",
            "ENTO",
            "FAES",
            "FMTP",
            "IGFS",
            "IPEA",
            "PATH",
            "SEAD",
            "SOIL",
            "WILD",
            "WOOD",
        ],
    ),
    (
        "Arts",
        "arts",
        [
            "ANTH",
            "ARTH",
            "CANS",
            "CLAS",
            "EAST",
            "ECON",
            "ENGL",
            "PHIL",
            "POLI",
            "PSYC",
            "RELG",
            "RELI",
            "HIST",
            "ISLA",
            "LING",
            "JWST",
            "SOCI",
            "SWRK",
            "URBS",
            "INTD",
            "WMST",
            "GERM",
            "SPAN",
            "ITAL",
            "PORT",
            "RUSS",
            "CHIN",
            "JPST",
            "ARAB",
            "HEBR",
        ],
    ),
    (
        "Dental Medicine & Oral Health Sciences",
        "dental",
        [
            "DENT",
            "MDNT",
            "ORCD",
        ],
    ),
    (
        "Education",
        "education",
        [
            "EDEC",
            "EDPE",
            "EDST",
            "EDSA",
            "EDKN",
            "EDLB",
            "EDLS",
            "EDPL",
            "EDUC",
            "KINE",
            "EDKP",
            "EDPC",
            "EDEM",
            "EDES",
            "EDPI",
            "EDSL",
        ],
    ),
    (
        "Engineering",
        "engineering",
        [
            "ECSE",
            "MECH",
            "CIVE",
            "MIME",
            "FACC",
            "CHEE",
            "MTLS",
            "ENVE",
            "BREE",
            "MIMI",
            "ENGR",
        ],
    ),
    (
        "Environment (Bieler School)",
        "environment",
        [
            "ENVB",
            "ENVR",
            "URBP",
        ],
    ),
    (
        "Law",
        "law",
        [
            "LAWS",
        ],
    ),
    (
        "Management (Desautels)",
        "management",
        [
            "ACCT",
            "FINE",
            "INSY",
            "MGCR",
            "MGMT",
            "MRKT",
            "ORGB",
            "STRA",
            "BUSA",
            "MGPO",
        ],
    ),
    (
        "Medicine & Health Sciences",
        "medicine",
        [
            "ANAT",
            "BIOC",
            "EPIB",
            "EXMD",
            "MEDC",
            "MICR",
            "NSCI",
            "NEUR",
            "PHAR",
            "PHGY",
            "PTOT",
            "REHB",
            "ORTH",
            "MDCN",
            "NUTR",
            "SPCH",
            "BMDE",
            "HGEN",
            "MIMM",
            "OCCH",
            "PATH",
            "PPHS",
            "PSYT",
            "SCSD",
            "REDM",
        ],
    ),
    (
        "Music (Schulich)",
        "music",
        [
            "MUAR",
            "MUSP",
            "MUTH",
        ],
    ),
    (
        "Nursing",
        "nursing",
        [
            "NURS",
        ],
    ),
    (
        "Science",
        "science",
        [
            "ATOC",
            "BIOL",
            "CHEM",
            "COMP",
            "EART",
            "GEOG",
            "MATH",
            "PHYS",
            "PSYC",
            "ANAT",
            "BIOC",
            "MICR",
            "PHAR",
            "PHGY",
            "NRSC",
            "BINF",
            "BIOT",
            "EPSC",
            "ESYS",
            "FSCI",
            "HSEL",
            "INTG",
            "WCOM",
        ],
    ),
]

PROGRAM_PAGES: dict[str, list[str]] = {
    "agri-env-sci": [
        "/en/undergraduate/agri-env-sci/",
        "/en/undergraduate/agri-env-sci/programs/",
        "/en/undergraduate/agri-env-sci/programs/foundation/",
        "/en/undergraduate/agri-env-sci/programs/animal-science/",
        "/en/undergraduate/agri-env-sci/programs/food-science-agricultural-chemistry/",
        "/en/undergraduate/agri-env-sci/programs/natural-resource-sciences/",
        "/en/undergraduate/agri-env-sci/programs/plant-science/",
        "/en/undergraduate/agri-env-sci/programs/bioresource-engineering/",
        "/en/undergraduate/agri-env-sci/programs/human-nutrition/",
        "/en/graduate/agri-env-sci/",
        "/en/graduate/agri-env-sci/food-science-agricultural-chemistry/",
    ],
    "arts": [
        "/en/undergraduate/arts/",
        "/en/undergraduate/arts/programs/",
        "/en/undergraduate/arts/degree-requirements/about-program/",
        "/en/undergraduate/arts/degree-requirements/about-program/foundation-program-general-ba/",
        "/en/undergraduate/arts/programs/economics/",
        "/en/undergraduate/arts/programs/political-science/",
        "/en/undergraduate/arts/programs/psychology/",
        "/en/undergraduate/arts/programs/sociology/",
        "/en/undergraduate/arts/programs/history/",
        "/en/undergraduate/arts/programs/philosophy/",
        "/en/undergraduate/arts/programs/linguistics/",
        "/en/graduate/arts/",
    ],
    "arts-science": [
        "/en/undergraduate/arts-science/",
        "/en/undergraduate/arts-science/overview-programs-offered/",
        "/en/undergraduate/arts-science/overview-programs-offered/basc-foundation-year-program/",
        "/en/undergraduate/arts-science/overview-programs-offered/basc-foundation-year-program/foundation-year-program-basc/",
    ],
    "dental": [
        "/en/undergraduate/dental/",
        "/en/graduate/dental/",
    ],
    "education": [
        "/en/undergraduate/education/",
        "/en/undergraduate/education/programs/",
        "/en/graduate/education/",
    ],
    "engineering": [
        "/en/undergraduate/engineering/",
        "/en/undergraduate/engineering/programs/",
        "/en/undergraduate/engineering/programs/electrical-computer/",
        "/en/undergraduate/engineering/programs/mechanical/",
        "/en/undergraduate/engineering/programs/civil/",
        "/en/undergraduate/engineering/programs/chemical/",
        "/en/undergraduate/engineering/programs/materials/",
        "/en/graduate/engineering/",
    ],
    "environment": [
        "/en/undergraduate/environment/",
        "/en/graduate/environment/",
    ],
    "law": [
        "/en/undergraduate/law/",
        "/en/graduate/law/",
    ],
    "management": [
        "/en/undergraduate/management/",
        "/en/undergraduate/management/programs/",
        "/en/graduate/management/",
    ],
    "medicine": [
        "/en/undergraduate/medicine/",
        "/en/graduate/medicine/",
        "/en/graduate/medicine/biochemistry/",
        "/en/graduate/medicine/epidemiology-biostatistics/",
        "/en/graduate/medicine/microbiology-immunology/",
        "/en/graduate/medicine/pharmacology-therapeutics/",
        "/en/graduate/medicine/physiology/",
        "/en/graduate/medicine/neuroscience/",
    ],
    "music": [
        "/en/undergraduate/music/",
        "/en/graduate/music/",
    ],
    "nursing": [
        "/en/undergraduate/nursing/",
        "/en/graduate/nursing/",
    ],
    "science": [
        "/en/undergraduate/science/",
        "/en/undergraduate/science/programs/",
        "/en/undergraduate/science/overview-programs-offered/sci-foundation-program/",
        "/en/undergraduate/science/overview-programs-offered/sci-foundation-program/foundation-year/",
        "/en/undergraduate/science/programs/biology/",
        "/en/undergraduate/science/programs/chemistry-programs/",
        "/en/undergraduate/science/programs/computer-science-programs/",
        "/en/undergraduate/science/programs/mathematics-statistics-programs/",
        "/en/undergraduate/science/programs/physics/",
        "/en/undergraduate/science/programs/psychology-programs/",
        "/en/undergraduate/science/programs/biochemistry-programs/",
        "/en/undergraduate/science/programs/microbiology-immunology/",
        "/en/undergraduate/science/programs/earth-planetary-sciences/",
        "/en/graduate/science/",
        "/en/graduate/science/biology/",
        "/en/graduate/science/chemistry/",
        "/en/graduate/science/computer-science/",
        "/en/graduate/science/mathematics-statistics/",
        "/en/graduate/science/physics/",
        "/en/graduate/science/psychology/",
    ],
}


DEPARTMENT_WEBSITES: dict[str, str] = {
    # Agricultural & Environmental Sciences
    "AGRI": "https://www.mcgill.ca/macdonald/",
    "ANSC": "https://www.mcgill.ca/animal/",
    "FDSC": "https://www.mcgill.ca/foodscience/",
    "PLNT": "https://www.mcgill.ca/plant/",
    "NRSC": "https://www.mcgill.ca/nrs/",
    "AEBI": "https://www.mcgill.ca/bioeng/",
    "LSCI": "https://www.mcgill.ca/lifesciences/",
    "ABEN": "https://www.mcgill.ca/bioeng/",
    "BIEN": "https://www.mcgill.ca/bioeng/",
    "BREE": "https://www.mcgill.ca/bioeng/",
    "PARA": "https://www.mcgill.ca/parasitology/",
    "NUTR": "https://www.mcgill.ca/humannutrition/",
    # Arts
    "ANTH": "https://www.mcgill.ca/anthropology/",
    "ECON": "https://www.mcgill.ca/economics/",
    "ENGL": "https://www.mcgill.ca/english/",
    "HIST": "https://www.mcgill.ca/history/",
    "LING": "https://www.mcgill.ca/linguistics/",
    "PHIL": "https://www.mcgill.ca/philosophy/",
    "POLI": "https://www.mcgill.ca/politicalscience/",
    "PSYC": "https://www.mcgill.ca/psychology/",
    "SOCI": "https://www.mcgill.ca/sociology/",
    "ARTH": "https://www.mcgill.ca/ahcs/",
    "CLAS": "https://www.mcgill.ca/classics/",
    "RELG": "https://www.mcgill.ca/religiousstudies/",
    "SWRK": "https://www.mcgill.ca/socialwork/",
    # Engineering
    "ECSE": "https://www.mcgill.ca/ece/",
    "MECH": "https://www.mcgill.ca/mecheng/",
    "CIVE": "https://www.mcgill.ca/civil/",
    "CHEE": "https://www.mcgill.ca/chemeng/",
    "MIME": "https://www.mcgill.ca/minmet/",
    "MTLS": "https://www.mcgill.ca/minmet/",
    # Science
    "BIOL": "https://www.mcgill.ca/biology/",
    "CHEM": "https://www.mcgill.ca/chemistry/",
    "COMP": "https://www.cs.mcgill.ca/",
    "MATH": "https://www.mcgill.ca/mathstat/",
    "PHYS": "https://www.physics.mcgill.ca/",
    "ATOC": "https://www.mcgill.ca/meteo/",
    "EART": "https://www.mcgill.ca/eps/",
    "GEOG": "https://www.mcgill.ca/geography/",
    # Medicine & Health Sciences
    "ANAT": "https://www.mcgill.ca/anatomy/",
    "BIOC": "https://www.mcgill.ca/biochemistry/",
    "EPIB": "https://www.mcgill.ca/epi-biostat-occh/",
    "MICR": "https://www.mcgill.ca/microimm/",
    "PHAR": "https://www.mcgill.ca/pharma/",
    "PHGY": "https://www.mcgill.ca/physiology/",
    "NEUR": "https://www.mcgill.ca/neuro/",
    "NSCI": "https://www.mcgill.ca/neuro/",
    # Management (Desautels)
    "ACCT": "https://www.mcgill.ca/desautels/",
    "FINE": "https://www.mcgill.ca/desautels/",
    "MGCR": "https://www.mcgill.ca/desautels/",
    "MGMT": "https://www.mcgill.ca/desautels/",
    "MRKT": "https://www.mcgill.ca/desautels/",
    "ORGB": "https://www.mcgill.ca/desautels/",
    # Other faculties
    "LAWS": "https://www.mcgill.ca/law/",
    "DENT": "https://www.mcgill.ca/dentistry/",
    "NURS": "https://www.mcgill.ca/nursing/",
    "MUAR": "https://www.mcgill.ca/music/",
    "MUSP": "https://www.mcgill.ca/music/",
    "MUTH": "https://www.mcgill.ca/music/",
    "EDUC": "https://www.mcgill.ca/education/",
    "KINE": "https://www.mcgill.ca/edu-kpe/",
    "ENVR": "https://www.mcgill.ca/bieler/",
    "ENVB": "https://www.mcgill.ca/bieler/",
}


DEPARTMENT_RESOURCES: dict[str, dict[str, str | list[str]]] = {
    "FDSC": {
        "student_society": "McGill Food Science Association (FSA)",
        "student_society_url": "https://mcgillfsa.wixsite.com/home",
        "library_guide": "https://libraryguides.mcgill.ca/food-science",
        "foundation_email": "foundationyear.macdonald@mcgill.ca",
        "freshman_advisor_email": "freshmanadvisor.macdonald@mcgill.ca",
        "campus": "Macdonald Campus",
        "building": "Macdonald-Stewart Building, Room MS1-033",
    },
    "ANSC": {
        "foundation_email": "foundationyear.macdonald@mcgill.ca",
        "freshman_advisor_email": "freshmanadvisor.macdonald@mcgill.ca",
        "campus": "Macdonald Campus",
    },
    "PLNT": {
        "foundation_email": "foundationyear.macdonald@mcgill.ca",
        "freshman_advisor_email": "freshmanadvisor.macdonald@mcgill.ca",
        "campus": "Macdonald Campus",
    },
    "NRSC": {
        "foundation_email": "foundationyear.macdonald@mcgill.ca",
        "freshman_advisor_email": "freshmanadvisor.macdonald@mcgill.ca",
        "campus": "Macdonald Campus",
    },
    "ABEN": {
        "foundation_email": "foundationyear.macdonald@mcgill.ca",
        "freshman_advisor_email": "freshmanadvisor.macdonald@mcgill.ca",
        "campus": "Macdonald Campus",
    },
    "BIEN": {
        "foundation_email": "foundationyear.macdonald@mcgill.ca",
        "freshman_advisor_email": "freshmanadvisor.macdonald@mcgill.ca",
        "campus": "Macdonald Campus",
    },
    "BREE": {
        "foundation_email": "foundationyear.macdonald@mcgill.ca",
        "freshman_advisor_email": "freshmanadvisor.macdonald@mcgill.ca",
        "campus": "Macdonald Campus",
    },
    "LSCI": {
        "foundation_email": "foundationyear.macdonald@mcgill.ca",
        "freshman_advisor_email": "freshmanadvisor.macdonald@mcgill.ca",
        "campus": "Macdonald Campus",
    },
    "COMP": {
        "student_society": "Computer Science Undergraduate Society (CSUS)",
        "student_society_url": "https://csus.cs.mcgill.ca/",
        "library_guide": "https://libraryguides.mcgill.ca/computer-science",
    },
    "MATH": {
        "student_society": "Mathematics and Statistics Students' Association (MASSA)",
        "library_guide": "https://libraryguides.mcgill.ca/math-stats",
    },
    "PHYS": {
        "student_society": "McGill Physics Students' Association (MPSA)",
        "library_guide": "https://libraryguides.mcgill.ca/physics",
    },
    "BIOL": {
        "student_society": "Biology Students' Association (BSA)",
        "library_guide": "https://libraryguides.mcgill.ca/biology",
    },
    "CHEM": {
        "student_society": "Chemistry Students' Association (ChemSA)",
        "library_guide": "https://libraryguides.mcgill.ca/chemistry",
    },
    "PSYC": {
        "student_society": "Psychology Students' Association (PSA)",
        "library_guide": "https://libraryguides.mcgill.ca/psychology",
    },
    "ECSE": {
        "student_society": "Electrical, Computer and Software Engineering Students' Society (ECSESS)",
    },
    "MECH": {
        "student_society": "Mechanical Engineering Students' Association (MESA)",
    },
}

FACULTY_RESOURCES: dict[str, dict[str, str]] = {
    "agri-env-sci": {
        "students_society": "Macdonald Campus Students' Society (MCSS)",
        "students_society_url": "https://mcssmcgill.ca/",
        "foundation_email": "foundationyear.macdonald@mcgill.ca",
        "foundation_page": "https://coursecatalogue.mcgill.ca/en/undergraduate/agri-env-sci/programs/foundation/",
    },
    "science": {
        "foundation_page": "https://coursecatalogue.mcgill.ca/en/undergraduate/science/overview-programs-offered/sci-foundation-program/foundation-year/",
        "foundation_planner": "https://www.mcgill.ca/science/files/science/bachelor_of_science_foundation_program_planner.pdf",
        "foundation_checklist": "https://www.mcgill.ca/science/undergraduate/accepted/checklist/firstyear/foundation",
    },
    "arts": {
        "foundation_page": "https://coursecatalogue.mcgill.ca/en/undergraduate/arts/degree-requirements/about-program/foundation-program-general-ba/",
    },
    "arts-science": {
        "foundation_page": "https://coursecatalogue.mcgill.ca/en/undergraduate/arts-science/overview-programs-offered/basc-foundation-year-program/foundation-year-program-basc/",
        "foundation_checklist": "https://www.mcgill.ca/science/undergraduate/accepted/checklist/firstyear/bascfreshman",
    },
}


def get_active_faculties(
    faculty_filter: list[str] | None = None,
) -> list[tuple[str, str, list[str]]]:
    if faculty_filter is None:
        return ALL_FACULTIES
    allowed = {v.lower() for v in faculty_filter}
    result = [
        f for f in ALL_FACULTIES if f[0].lower() in allowed or f[1].lower() in allowed
    ]
    if result:
        return result
    # Substring match as fallback for partial/inexact faculty names
    return [
        f
        for f in ALL_FACULTIES
        if any(
            a in f[0].lower() or f[0].lower() in a or a in f[1].lower() for a in allowed
        )
    ]
